grafana:
  adminUser: admin
  adminPassword: admin123
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
prometheus:
  prometheusSpec:
    retention: 7d

