apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps
  namespace: argocd
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    # 1) Chart Helm oficial
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 55.0.0
      helm:
        valueFiles:
          - $values/kps/values.yaml
    # 2) Tus values desde tu repo
    - repoURL: https://github.com/DiegoFGarc/argo-monitoring-dok
      targetRevision: main
      ref: values
      path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
