apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: '>=55.0.0'        # usa la version que se requiera
    helm:
      valueFiles:
        - values.yaml
      values: ""                      # opcional
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://github.com/DiegoFGarc/argo-monitoring-dok'
      targetRevision: main
      path: kps
