grafana:
  enabled: false
loki:
  auth_enabled: false
  persistence:
    enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
